services:
  # Downloader Container
  downloader:
    build:
      context: .
    image: downloader:dev
    user: "1000:1000"
    container_name: downloader
    env_file: .env
    restart: unless-stopped
    ports:
      - 5000:5000
    # Optional - alternative address used for autodiscovery
    environment:
      - TZ=America/New_York
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - HITS=${HITS}
      - FREE=${FREE}
      - MANY=${MANY}
      - URL_PROCESSOR=${URL_PROCESSOR}
      - CHECK_URL=${CHECK_URL}
      - UPLOAD_URL=${UPLOAD_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - /home/wilabeast/videos:/app/videos
      - /home/wilabeast/logs:/app/log/
    networks:
      - app-net

  # Celery Worker Container
  downloader-celery-worker:
    build:
      context: .
    image: downloader:dev
    user: "1000:1000"
    container_name: celery_worker_downloader
    command: celery -A src.configuration.celery_app worker -Q downloader_queue -l info --events
    volumes:
      - /home/wilabeast/videos:/app/videos
      - /home/wilabeast/logs:/app/log/
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      - downloader

networks:
  app-net:
    external: true